{
 "title": "Custom",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "query": {
     "query": "label_values(weather_temperature_celsius, city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "В какое время суток ветер был сильнее всего",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    { "expr": "weather_windspeed_kmh", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Влажность:",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_humidity_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "1-Day / 0-Night",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_is_day", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Облачность (покрытие):",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_cloudcover_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Сглаженная средняя температура за час",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius[1h])",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Показывает текущую температуру",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Как \"ощущается\" температура",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_apparent_temperature_celsius{city=\"Astana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Как быстро меняется давление",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "delta(weather_pressure_msl_hpa[30m])",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 15 },
   "targets": [
    { "expr": "weather_windspeed_kmh", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "API up or down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Осадки по часам",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 23 },
   "targets": [
    { "expr": "weather_precipitation_mm", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}