{
 "title": "Node ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Доля времени (от 0 до 1), которую CPU тратил на активную работу(min))",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{instance=\"node-exporter:9100\", mode!=\"idle\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Количество активных процессов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Системный Uptime (в днях)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds) / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average 1мин (5 мин) 15мин ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{__name__}}" },
    { "expr": "node_load5", "legendFormat": "{{__name__}}" },
    { "expr": "node_load15", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Входящий и исходящий сетевой трафик (в Мбит/сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[5m]) * 8 / 1000000",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[5m]) * 8 / 1000000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O — чтение и запись (байт/сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Memory (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/host/c\"} / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (в %) по ядрам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}